type User {
  name: String! @unique
  employees: [Employee]! @relation
  areas: [Area] @relation
  shifts: [Shift] @relation
  companyName: String
}

type Employee {
  name: String!
  email: String
  phone: String
  address: String
  manager: User!
  hourlyWage: Int
  emergencyContact: EmergencyContact
}

type EmergencyContact @embedded {
  name: String
  phone: String
}

type Shift {
  start: Date!
  finish: Date!
  creator: User!
  break: Int
  assignedTo: Employee # If null, default to open shift on client
  notes: String
  area: Area!
}

type Area {
  name: String!
  company: User!
  color: String!
}
