type User {
  name: String! @unique
	employees: [Employee]! @relation
}

type Employee {
	name: String!
	email: String
	phone: String
	manager: User!
	hourlyWage: Int!
}

type Area {
  name: String!
  color: String!
}


type Shift {
	start: Date!
	end: Date!
	break: Int
	notes: String
	creator: User!
	assignedTo: Employee!
	area: Area!
}









